// Code generated by protoc-gen-go. DO NOT EDIT.
// source: operator/controlplane/v1alpha1/values_types.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	common "github.com/tetrateio/api/operator/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Values configuration composition
type Values struct {
	Global               *GlobalConfig  `protobuf:"bytes,1,opt,name=global,proto3" json:"global,omitempty"`
	Tsbd                 *TsbdConfig    `protobuf:"bytes,2,opt,name=tsbd,proto3" json:"tsbd,omitempty"`
	Oap                  *OapConfig     `protobuf:"bytes,3,opt,name=oap,proto3" json:"oap,omitempty"`
	Tracing              *TracingConfig `protobuf:"bytes,4,opt,name=tracing,proto3" json:"tracing,omitempty"`
	Opentelemetry        *OpentelConfig `protobuf:"bytes,5,opt,name=opentelemetry,proto3" json:"opentelemetry,omitempty"`
	Iop                  *IOPConfig     `protobuf:"bytes,6,opt,name=iop,proto3" json:"iop,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Values) Reset()         { *m = Values{} }
func (m *Values) String() string { return proto.CompactTextString(m) }
func (*Values) ProtoMessage()    {}
func (*Values) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{0}
}

func (m *Values) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Values.Unmarshal(m, b)
}
func (m *Values) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Values.Marshal(b, m, deterministic)
}
func (m *Values) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Values.Merge(m, src)
}
func (m *Values) XXX_Size() int {
	return xxx_messageInfo_Values.Size(m)
}
func (m *Values) XXX_DiscardUnknown() {
	xxx_messageInfo_Values.DiscardUnknown(m)
}

var xxx_messageInfo_Values proto.InternalMessageInfo

func (m *Values) GetGlobal() *GlobalConfig {
	if m != nil {
		return m.Global
	}
	return nil
}

func (m *Values) GetTsbd() *TsbdConfig {
	if m != nil {
		return m.Tsbd
	}
	return nil
}

func (m *Values) GetOap() *OapConfig {
	if m != nil {
		return m.Oap
	}
	return nil
}

func (m *Values) GetTracing() *TracingConfig {
	if m != nil {
		return m.Tracing
	}
	return nil
}

func (m *Values) GetOpentelemetry() *OpentelConfig {
	if m != nil {
		return m.Opentelemetry
	}
	return nil
}

func (m *Values) GetIop() *IOPConfig {
	if m != nil {
		return m.Iop
	}
	return nil
}

// Global Configuration for TSB Management Plane components.
type GlobalConfig struct {
	// Specifies the docker hub for TSB images.
	Hub                  string                      `protobuf:"bytes,1,opt,name=hub,proto3" json:"hub,omitempty"`
	Tcc                  *GlobalConfig_TSBServer     `protobuf:"bytes,2,opt,name=tcc,proto3" json:"tcc,omitempty"`
	Elasticsearch        *GlobalConfig_ElasticSearch `protobuf:"bytes,3,opt,name=elasticsearch,proto3" json:"elasticsearch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GlobalConfig) Reset()         { *m = GlobalConfig{} }
func (m *GlobalConfig) String() string { return proto.CompactTextString(m) }
func (*GlobalConfig) ProtoMessage()    {}
func (*GlobalConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{1}
}

func (m *GlobalConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalConfig.Unmarshal(m, b)
}
func (m *GlobalConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalConfig.Marshal(b, m, deterministic)
}
func (m *GlobalConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalConfig.Merge(m, src)
}
func (m *GlobalConfig) XXX_Size() int {
	return xxx_messageInfo_GlobalConfig.Size(m)
}
func (m *GlobalConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalConfig proto.InternalMessageInfo

func (m *GlobalConfig) GetHub() string {
	if m != nil {
		return m.Hub
	}
	return ""
}

func (m *GlobalConfig) GetTcc() *GlobalConfig_TSBServer {
	if m != nil {
		return m.Tcc
	}
	return nil
}

func (m *GlobalConfig) GetElasticsearch() *GlobalConfig_ElasticSearch {
	if m != nil {
		return m.Elasticsearch
	}
	return nil
}

// tsb api server endpoint details
type GlobalConfig_TSBServer struct {
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Tenant               string   `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Cluster              string   `protobuf:"bytes,5,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Environment          string   `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalConfig_TSBServer) Reset()         { *m = GlobalConfig_TSBServer{} }
func (m *GlobalConfig_TSBServer) String() string { return proto.CompactTextString(m) }
func (*GlobalConfig_TSBServer) ProtoMessage()    {}
func (*GlobalConfig_TSBServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{1, 0}
}

func (m *GlobalConfig_TSBServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalConfig_TSBServer.Unmarshal(m, b)
}
func (m *GlobalConfig_TSBServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalConfig_TSBServer.Marshal(b, m, deterministic)
}
func (m *GlobalConfig_TSBServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalConfig_TSBServer.Merge(m, src)
}
func (m *GlobalConfig_TSBServer) XXX_Size() int {
	return xxx_messageInfo_GlobalConfig_TSBServer.Size(m)
}
func (m *GlobalConfig_TSBServer) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalConfig_TSBServer.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalConfig_TSBServer proto.InternalMessageInfo

func (m *GlobalConfig_TSBServer) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *GlobalConfig_TSBServer) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *GlobalConfig_TSBServer) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *GlobalConfig_TSBServer) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *GlobalConfig_TSBServer) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

// elasticsearch related values
type GlobalConfig_ElasticSearch struct {
	User                 string                          `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Password             string                          `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Ssl                  *GlobalConfig_ElasticSearch_Ssl `protobuf:"bytes,6,opt,name=ssl,proto3" json:"ssl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *GlobalConfig_ElasticSearch) Reset()         { *m = GlobalConfig_ElasticSearch{} }
func (m *GlobalConfig_ElasticSearch) String() string { return proto.CompactTextString(m) }
func (*GlobalConfig_ElasticSearch) ProtoMessage()    {}
func (*GlobalConfig_ElasticSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{1, 1}
}

func (m *GlobalConfig_ElasticSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalConfig_ElasticSearch.Unmarshal(m, b)
}
func (m *GlobalConfig_ElasticSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalConfig_ElasticSearch.Marshal(b, m, deterministic)
}
func (m *GlobalConfig_ElasticSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalConfig_ElasticSearch.Merge(m, src)
}
func (m *GlobalConfig_ElasticSearch) XXX_Size() int {
	return xxx_messageInfo_GlobalConfig_ElasticSearch.Size(m)
}
func (m *GlobalConfig_ElasticSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalConfig_ElasticSearch.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalConfig_ElasticSearch proto.InternalMessageInfo

func (m *GlobalConfig_ElasticSearch) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *GlobalConfig_ElasticSearch) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *GlobalConfig_ElasticSearch) GetSsl() *GlobalConfig_ElasticSearch_Ssl {
	if m != nil {
		return m.Ssl
	}
	return nil
}

type GlobalConfig_ElasticSearch_Ssl struct {
	Enabled              *wrappers.BoolValue `protobuf:"bytes,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GlobalConfig_ElasticSearch_Ssl) Reset()         { *m = GlobalConfig_ElasticSearch_Ssl{} }
func (m *GlobalConfig_ElasticSearch_Ssl) String() string { return proto.CompactTextString(m) }
func (*GlobalConfig_ElasticSearch_Ssl) ProtoMessage()    {}
func (*GlobalConfig_ElasticSearch_Ssl) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{1, 1, 0}
}

func (m *GlobalConfig_ElasticSearch_Ssl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalConfig_ElasticSearch_Ssl.Unmarshal(m, b)
}
func (m *GlobalConfig_ElasticSearch_Ssl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalConfig_ElasticSearch_Ssl.Marshal(b, m, deterministic)
}
func (m *GlobalConfig_ElasticSearch_Ssl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalConfig_ElasticSearch_Ssl.Merge(m, src)
}
func (m *GlobalConfig_ElasticSearch_Ssl) XXX_Size() int {
	return xxx_messageInfo_GlobalConfig_ElasticSearch_Ssl.Size(m)
}
func (m *GlobalConfig_ElasticSearch_Ssl) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalConfig_ElasticSearch_Ssl.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalConfig_ElasticSearch_Ssl proto.InternalMessageInfo

func (m *GlobalConfig_ElasticSearch_Ssl) GetEnabled() *wrappers.BoolValue {
	if m != nil {
		return m.Enabled
	}
	return nil
}

type TsbdConfig struct {
	Disableauthz         *wrappers.BoolValue `protobuf:"bytes,1,opt,name=disableauthz,proto3" json:"disableauthz,omitempty"`
	Token                string              `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TsbdConfig) Reset()         { *m = TsbdConfig{} }
func (m *TsbdConfig) String() string { return proto.CompactTextString(m) }
func (*TsbdConfig) ProtoMessage()    {}
func (*TsbdConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{2}
}

func (m *TsbdConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TsbdConfig.Unmarshal(m, b)
}
func (m *TsbdConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TsbdConfig.Marshal(b, m, deterministic)
}
func (m *TsbdConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TsbdConfig.Merge(m, src)
}
func (m *TsbdConfig) XXX_Size() int {
	return xxx_messageInfo_TsbdConfig.Size(m)
}
func (m *TsbdConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TsbdConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TsbdConfig proto.InternalMessageInfo

func (m *TsbdConfig) GetDisableauthz() *wrappers.BoolValue {
	if m != nil {
		return m.Disableauthz
	}
	return nil
}

func (m *TsbdConfig) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type OapConfig struct {
	EnabledPackedDownsampling *wrappers.BoolValue      `protobuf:"bytes,1,opt,name=enabledPackedDownsampling,proto3" json:"enabledPackedDownsampling,omitempty"`
	Analysis                  string                   `protobuf:"bytes,2,opt,name=analysis,proto3" json:"analysis,omitempty"`
	Token                     string                   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	LogLevel                  string                   `protobuf:"bytes,4,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	Resources                 *common.Resources        `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	Elasticsearch             *OapConfig_ElasticSearch `protobuf:"bytes,6,opt,name=elasticsearch,proto3" json:"elasticsearch,omitempty"`
	ExternalServices          *OapExternalServices     `protobuf:"bytes,7,opt,name=externalServices,proto3" json:"externalServices,omitempty"`
	DayStep                   int32                    `protobuf:"varint,8,opt,name=dayStep,proto3" json:"dayStep,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                 `json:"-"`
	XXX_unrecognized          []byte                   `json:"-"`
	XXX_sizecache             int32                    `json:"-"`
}

func (m *OapConfig) Reset()         { *m = OapConfig{} }
func (m *OapConfig) String() string { return proto.CompactTextString(m) }
func (*OapConfig) ProtoMessage()    {}
func (*OapConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{3}
}

func (m *OapConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OapConfig.Unmarshal(m, b)
}
func (m *OapConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OapConfig.Marshal(b, m, deterministic)
}
func (m *OapConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OapConfig.Merge(m, src)
}
func (m *OapConfig) XXX_Size() int {
	return xxx_messageInfo_OapConfig.Size(m)
}
func (m *OapConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_OapConfig.DiscardUnknown(m)
}

var xxx_messageInfo_OapConfig proto.InternalMessageInfo

func (m *OapConfig) GetEnabledPackedDownsampling() *wrappers.BoolValue {
	if m != nil {
		return m.EnabledPackedDownsampling
	}
	return nil
}

func (m *OapConfig) GetAnalysis() string {
	if m != nil {
		return m.Analysis
	}
	return ""
}

func (m *OapConfig) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *OapConfig) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

func (m *OapConfig) GetResources() *common.Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *OapConfig) GetElasticsearch() *OapConfig_ElasticSearch {
	if m != nil {
		return m.Elasticsearch
	}
	return nil
}

func (m *OapConfig) GetExternalServices() *OapExternalServices {
	if m != nil {
		return m.ExternalServices
	}
	return nil
}

func (m *OapConfig) GetDayStep() int32 {
	if m != nil {
		return m.DayStep
	}
	return 0
}

// elasticsearch related values
type OapConfig_ElasticSearch struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	SecretFile           string   `protobuf:"bytes,3,opt,name=secretFile,proto3" json:"secretFile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OapConfig_ElasticSearch) Reset()         { *m = OapConfig_ElasticSearch{} }
func (m *OapConfig_ElasticSearch) String() string { return proto.CompactTextString(m) }
func (*OapConfig_ElasticSearch) ProtoMessage()    {}
func (*OapConfig_ElasticSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{3, 0}
}

func (m *OapConfig_ElasticSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OapConfig_ElasticSearch.Unmarshal(m, b)
}
func (m *OapConfig_ElasticSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OapConfig_ElasticSearch.Marshal(b, m, deterministic)
}
func (m *OapConfig_ElasticSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OapConfig_ElasticSearch.Merge(m, src)
}
func (m *OapConfig_ElasticSearch) XXX_Size() int {
	return xxx_messageInfo_OapConfig_ElasticSearch.Size(m)
}
func (m *OapConfig_ElasticSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_OapConfig_ElasticSearch.DiscardUnknown(m)
}

var xxx_messageInfo_OapConfig_ElasticSearch proto.InternalMessageInfo

func (m *OapConfig_ElasticSearch) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *OapConfig_ElasticSearch) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *OapConfig_ElasticSearch) GetSecretFile() string {
	if m != nil {
		return m.SecretFile
	}
	return ""
}

type OapExternalServices struct {
	Metadata             *OapExternalServices_MetaData      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Configuration        *OapExternalServices_Configuration `protobuf:"bytes,2,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Webhook              map[string]string                  `protobuf:"bytes,3,rep,name=webhook,proto3" json:"webhook,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *OapExternalServices) Reset()         { *m = OapExternalServices{} }
func (m *OapExternalServices) String() string { return proto.CompactTextString(m) }
func (*OapExternalServices) ProtoMessage()    {}
func (*OapExternalServices) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{4}
}

func (m *OapExternalServices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OapExternalServices.Unmarshal(m, b)
}
func (m *OapExternalServices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OapExternalServices.Marshal(b, m, deterministic)
}
func (m *OapExternalServices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OapExternalServices.Merge(m, src)
}
func (m *OapExternalServices) XXX_Size() int {
	return xxx_messageInfo_OapExternalServices.Size(m)
}
func (m *OapExternalServices) XXX_DiscardUnknown() {
	xxx_messageInfo_OapExternalServices.DiscardUnknown(m)
}

var xxx_messageInfo_OapExternalServices proto.InternalMessageInfo

func (m *OapExternalServices) GetMetadata() *OapExternalServices_MetaData {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *OapExternalServices) GetConfiguration() *OapExternalServices_Configuration {
	if m != nil {
		return m.Configuration
	}
	return nil
}

func (m *OapExternalServices) GetWebhook() map[string]string {
	if m != nil {
		return m.Webhook
	}
	return nil
}

type OapExternalServices_MetaData struct {
	Enabled              *wrappers.BoolValue `protobuf:"bytes,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Host                 string              `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32               `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *OapExternalServices_MetaData) Reset()         { *m = OapExternalServices_MetaData{} }
func (m *OapExternalServices_MetaData) String() string { return proto.CompactTextString(m) }
func (*OapExternalServices_MetaData) ProtoMessage()    {}
func (*OapExternalServices_MetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{4, 0}
}

func (m *OapExternalServices_MetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OapExternalServices_MetaData.Unmarshal(m, b)
}
func (m *OapExternalServices_MetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OapExternalServices_MetaData.Marshal(b, m, deterministic)
}
func (m *OapExternalServices_MetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OapExternalServices_MetaData.Merge(m, src)
}
func (m *OapExternalServices_MetaData) XXX_Size() int {
	return xxx_messageInfo_OapExternalServices_MetaData.Size(m)
}
func (m *OapExternalServices_MetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_OapExternalServices_MetaData.DiscardUnknown(m)
}

var xxx_messageInfo_OapExternalServices_MetaData proto.InternalMessageInfo

func (m *OapExternalServices_MetaData) GetEnabled() *wrappers.BoolValue {
	if m != nil {
		return m.Enabled
	}
	return nil
}

func (m *OapExternalServices_MetaData) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *OapExternalServices_MetaData) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type OapExternalServices_Configuration struct {
	Enabled              *wrappers.BoolValue `protobuf:"bytes,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ClusterName          string              `protobuf:"bytes,2,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	Period               int32               `protobuf:"varint,3,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *OapExternalServices_Configuration) Reset()         { *m = OapExternalServices_Configuration{} }
func (m *OapExternalServices_Configuration) String() string { return proto.CompactTextString(m) }
func (*OapExternalServices_Configuration) ProtoMessage()    {}
func (*OapExternalServices_Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{4, 1}
}

func (m *OapExternalServices_Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OapExternalServices_Configuration.Unmarshal(m, b)
}
func (m *OapExternalServices_Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OapExternalServices_Configuration.Marshal(b, m, deterministic)
}
func (m *OapExternalServices_Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OapExternalServices_Configuration.Merge(m, src)
}
func (m *OapExternalServices_Configuration) XXX_Size() int {
	return xxx_messageInfo_OapExternalServices_Configuration.Size(m)
}
func (m *OapExternalServices_Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_OapExternalServices_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_OapExternalServices_Configuration proto.InternalMessageInfo

func (m *OapExternalServices_Configuration) GetEnabled() *wrappers.BoolValue {
	if m != nil {
		return m.Enabled
	}
	return nil
}

func (m *OapExternalServices_Configuration) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *OapExternalServices_Configuration) GetPeriod() int32 {
	if m != nil {
		return m.Period
	}
	return 0
}

type TracingConfig struct {
	Elasticsearch        *TracingConfig_ElasticSearch `protobuf:"bytes,1,opt,name=elasticsearch,proto3" json:"elasticsearch,omitempty"`
	Zipkin               *TracingConfig_ZipkinConfig  `protobuf:"bytes,2,opt,name=zipkin,proto3" json:"zipkin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TracingConfig) Reset()         { *m = TracingConfig{} }
func (m *TracingConfig) String() string { return proto.CompactTextString(m) }
func (*TracingConfig) ProtoMessage()    {}
func (*TracingConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{5}
}

func (m *TracingConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TracingConfig.Unmarshal(m, b)
}
func (m *TracingConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TracingConfig.Marshal(b, m, deterministic)
}
func (m *TracingConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TracingConfig.Merge(m, src)
}
func (m *TracingConfig) XXX_Size() int {
	return xxx_messageInfo_TracingConfig.Size(m)
}
func (m *TracingConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TracingConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TracingConfig proto.InternalMessageInfo

func (m *TracingConfig) GetElasticsearch() *TracingConfig_ElasticSearch {
	if m != nil {
		return m.Elasticsearch
	}
	return nil
}

func (m *TracingConfig) GetZipkin() *TracingConfig_ZipkinConfig {
	if m != nil {
		return m.Zipkin
	}
	return nil
}

// elasticsearch related values
type TracingConfig_ElasticSearch struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TracingConfig_ElasticSearch) Reset()         { *m = TracingConfig_ElasticSearch{} }
func (m *TracingConfig_ElasticSearch) String() string { return proto.CompactTextString(m) }
func (*TracingConfig_ElasticSearch) ProtoMessage()    {}
func (*TracingConfig_ElasticSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{5, 0}
}

func (m *TracingConfig_ElasticSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TracingConfig_ElasticSearch.Unmarshal(m, b)
}
func (m *TracingConfig_ElasticSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TracingConfig_ElasticSearch.Marshal(b, m, deterministic)
}
func (m *TracingConfig_ElasticSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TracingConfig_ElasticSearch.Merge(m, src)
}
func (m *TracingConfig_ElasticSearch) XXX_Size() int {
	return xxx_messageInfo_TracingConfig_ElasticSearch.Size(m)
}
func (m *TracingConfig_ElasticSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_TracingConfig_ElasticSearch.DiscardUnknown(m)
}

var xxx_messageInfo_TracingConfig_ElasticSearch proto.InternalMessageInfo

func (m *TracingConfig_ElasticSearch) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *TracingConfig_ElasticSearch) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type TracingConfig_ZipkinConfig struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TracingConfig_ZipkinConfig) Reset()         { *m = TracingConfig_ZipkinConfig{} }
func (m *TracingConfig_ZipkinConfig) String() string { return proto.CompactTextString(m) }
func (*TracingConfig_ZipkinConfig) ProtoMessage()    {}
func (*TracingConfig_ZipkinConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{5, 1}
}

func (m *TracingConfig_ZipkinConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TracingConfig_ZipkinConfig.Unmarshal(m, b)
}
func (m *TracingConfig_ZipkinConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TracingConfig_ZipkinConfig.Marshal(b, m, deterministic)
}
func (m *TracingConfig_ZipkinConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TracingConfig_ZipkinConfig.Merge(m, src)
}
func (m *TracingConfig_ZipkinConfig) XXX_Size() int {
	return xxx_messageInfo_TracingConfig_ZipkinConfig.Size(m)
}
func (m *TracingConfig_ZipkinConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TracingConfig_ZipkinConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TracingConfig_ZipkinConfig proto.InternalMessageInfo

func (m *TracingConfig_ZipkinConfig) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type OpentelConfig struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpentelConfig) Reset()         { *m = OpentelConfig{} }
func (m *OpentelConfig) String() string { return proto.CompactTextString(m) }
func (*OpentelConfig) ProtoMessage()    {}
func (*OpentelConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{6}
}

func (m *OpentelConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpentelConfig.Unmarshal(m, b)
}
func (m *OpentelConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpentelConfig.Marshal(b, m, deterministic)
}
func (m *OpentelConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpentelConfig.Merge(m, src)
}
func (m *OpentelConfig) XXX_Size() int {
	return xxx_messageInfo_OpentelConfig.Size(m)
}
func (m *OpentelConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_OpentelConfig.DiscardUnknown(m)
}

var xxx_messageInfo_OpentelConfig proto.InternalMessageInfo

func (m *OpentelConfig) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type IOPConfig struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IOPConfig) Reset()         { *m = IOPConfig{} }
func (m *IOPConfig) String() string { return proto.CompactTextString(m) }
func (*IOPConfig) ProtoMessage()    {}
func (*IOPConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7537c8a30a2178, []int{7}
}

func (m *IOPConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IOPConfig.Unmarshal(m, b)
}
func (m *IOPConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IOPConfig.Marshal(b, m, deterministic)
}
func (m *IOPConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IOPConfig.Merge(m, src)
}
func (m *IOPConfig) XXX_Size() int {
	return xxx_messageInfo_IOPConfig.Size(m)
}
func (m *IOPConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IOPConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IOPConfig proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Values)(nil), "tetrateio.api.operator.controlplane.v1alpha1.Values")
	proto.RegisterType((*GlobalConfig)(nil), "tetrateio.api.operator.controlplane.v1alpha1.GlobalConfig")
	proto.RegisterType((*GlobalConfig_TSBServer)(nil), "tetrateio.api.operator.controlplane.v1alpha1.GlobalConfig.TSBServer")
	proto.RegisterType((*GlobalConfig_ElasticSearch)(nil), "tetrateio.api.operator.controlplane.v1alpha1.GlobalConfig.ElasticSearch")
	proto.RegisterType((*GlobalConfig_ElasticSearch_Ssl)(nil), "tetrateio.api.operator.controlplane.v1alpha1.GlobalConfig.ElasticSearch.Ssl")
	proto.RegisterType((*TsbdConfig)(nil), "tetrateio.api.operator.controlplane.v1alpha1.TsbdConfig")
	proto.RegisterType((*OapConfig)(nil), "tetrateio.api.operator.controlplane.v1alpha1.OapConfig")
	proto.RegisterType((*OapConfig_ElasticSearch)(nil), "tetrateio.api.operator.controlplane.v1alpha1.OapConfig.ElasticSearch")
	proto.RegisterType((*OapExternalServices)(nil), "tetrateio.api.operator.controlplane.v1alpha1.OapExternalServices")
	proto.RegisterMapType((map[string]string)(nil), "tetrateio.api.operator.controlplane.v1alpha1.OapExternalServices.WebhookEntry")
	proto.RegisterType((*OapExternalServices_MetaData)(nil), "tetrateio.api.operator.controlplane.v1alpha1.OapExternalServices.MetaData")
	proto.RegisterType((*OapExternalServices_Configuration)(nil), "tetrateio.api.operator.controlplane.v1alpha1.OapExternalServices.Configuration")
	proto.RegisterType((*TracingConfig)(nil), "tetrateio.api.operator.controlplane.v1alpha1.TracingConfig")
	proto.RegisterType((*TracingConfig_ElasticSearch)(nil), "tetrateio.api.operator.controlplane.v1alpha1.TracingConfig.ElasticSearch")
	proto.RegisterType((*TracingConfig_ZipkinConfig)(nil), "tetrateio.api.operator.controlplane.v1alpha1.TracingConfig.ZipkinConfig")
	proto.RegisterType((*OpentelConfig)(nil), "tetrateio.api.operator.controlplane.v1alpha1.OpentelConfig")
	proto.RegisterType((*IOPConfig)(nil), "tetrateio.api.operator.controlplane.v1alpha1.IOPConfig")
}

func init() {
	proto.RegisterFile("operator/controlplane/v1alpha1/values_types.proto", fileDescriptor_1e7537c8a30a2178)
}

var fileDescriptor_1e7537c8a30a2178 = []byte{
	// 953 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x41, 0x6f, 0x23, 0x35,
	0x14, 0xc7, 0x95, 0x4e, 0x9a, 0x34, 0x2f, 0x8d, 0xb4, 0x32, 0x08, 0x85, 0x39, 0xac, 0xa2, 0x08,
	0xa4, 0x1e, 0xd0, 0x44, 0x5d, 0x90, 0xba, 0x74, 0x25, 0x24, 0xba, 0xed, 0xb2, 0x45, 0x65, 0xbb,
	0x9a, 0x2c, 0xbb, 0x68, 0x0f, 0x80, 0x67, 0xf2, 0x9a, 0x8c, 0xe2, 0xd8, 0x96, 0xed, 0x49, 0xc9,
	0x5e, 0x38, 0x21, 0x3e, 0x17, 0x57, 0x6e, 0xdc, 0xf9, 0x24, 0x9c, 0x90, 0x1d, 0x4f, 0x3a, 0x29,
	0x6d, 0x69, 0x92, 0xbd, 0xcd, 0x9b, 0x19, 0xff, 0xfe, 0xcf, 0x7e, 0x7e, 0x7f, 0x1b, 0xf6, 0x85,
	0x44, 0x45, 0x8d, 0x50, 0xbd, 0x54, 0x70, 0xa3, 0x04, 0x93, 0x8c, 0x72, 0xec, 0x4d, 0xf7, 0x29,
	0x93, 0x23, 0xba, 0xdf, 0x9b, 0x52, 0x96, 0xa3, 0xfe, 0xc9, 0xcc, 0x24, 0xea, 0x48, 0x2a, 0x61,
	0x04, 0xf9, 0xcc, 0xa0, 0x51, 0xd4, 0x60, 0x26, 0x22, 0x2a, 0xb3, 0xa8, 0x00, 0x44, 0x65, 0x40,
	0x54, 0x00, 0xc2, 0x87, 0x43, 0x21, 0x86, 0x0c, 0x7b, 0x6e, 0x6c, 0x92, 0x5f, 0xf4, 0x2e, 0x15,
	0x95, 0x12, 0x95, 0xa7, 0x85, 0x9d, 0x52, 0x02, 0x93, 0x89, 0xe0, 0xbd, 0x71, 0x9e, 0xa0, 0xe2,
	0x68, 0x0a, 0xbd, 0xee, 0x3f, 0x01, 0xd4, 0x5e, 0xbb, 0x34, 0x48, 0x0c, 0xb5, 0x21, 0x13, 0x09,
	0x65, 0xed, 0x4a, 0xa7, 0xb2, 0xd7, 0x7c, 0x74, 0x18, 0xad, 0x92, 0x4b, 0xf4, 0x8d, 0x1b, 0xfb,
	0x54, 0xf0, 0x8b, 0x6c, 0x18, 0x7b, 0x12, 0x39, 0x83, 0xaa, 0xd1, 0xc9, 0xa0, 0xbd, 0xe5, 0x88,
	0x8f, 0x57, 0x23, 0xbe, 0xd2, 0xc9, 0xc0, 0xf3, 0x1c, 0x85, 0x9c, 0x42, 0x20, 0xa8, 0x6c, 0x07,
	0x0e, 0x76, 0xb0, 0x1a, 0xec, 0x9c, 0x4a, 0xcf, 0xb2, 0x0c, 0xf2, 0x3d, 0xd4, 0x8d, 0xa2, 0x69,
	0xc6, 0x87, 0xed, 0xaa, 0xc3, 0x3d, 0x59, 0x31, 0xb7, 0xf9, 0x60, 0x8f, 0x2c, 0x58, 0x84, 0x42,
	0x4b, 0x48, 0xe4, 0x06, 0x19, 0x4e, 0xd0, 0xa8, 0x59, 0x7b, 0x7b, 0x1d, 0xf8, 0xf9, 0x1c, 0xe1,
	0xe1, 0xcb, 0x44, 0xbb, 0x08, 0x99, 0x90, 0xed, 0xda, 0x3a, 0x8b, 0x70, 0x7a, 0xfe, 0xb2, 0x58,
	0x84, 0x4c, 0xc8, 0xee, 0x5f, 0x55, 0xd8, 0x2d, 0x97, 0x8d, 0x3c, 0x80, 0x60, 0x94, 0x27, 0xae,
	0xfe, 0x8d, 0xd8, 0x3e, 0x92, 0xd7, 0x10, 0x98, 0x34, 0xf5, 0xf5, 0x3b, 0x5e, 0x7f, 0x47, 0x44,
	0xaf, 0xfa, 0x47, 0x7d, 0x54, 0x53, 0x54, 0xb1, 0x05, 0x12, 0x0e, 0x2d, 0x64, 0x54, 0x9b, 0x2c,
	0xd5, 0x48, 0x55, 0x3a, 0xf2, 0x45, 0x7d, 0xbe, 0x81, 0xc2, 0xc9, 0x9c, 0xd7, 0x77, 0xbc, 0x78,
	0x19, 0x1f, 0xfe, 0x5e, 0x81, 0xc6, 0x22, 0x05, 0x42, 0xa0, 0x3a, 0x12, 0xda, 0xb8, 0x69, 0x35,
	0x62, 0xf7, 0x6c, 0xdf, 0x49, 0xa1, 0x8c, 0x4b, 0x64, 0x3b, 0x76, 0xcf, 0xe4, 0x23, 0xa8, 0x19,
	0xe4, 0x94, 0x1b, 0xb7, 0x49, 0x1a, 0xb1, 0x8f, 0x48, 0x1b, 0xea, 0x29, 0xcb, 0xb5, 0x41, 0xe5,
	0x0a, 0xdc, 0x88, 0x8b, 0x90, 0x74, 0xa0, 0x89, 0x7c, 0x9a, 0x29, 0xc1, 0x27, 0xc8, 0x8d, 0xab,
	0x52, 0x23, 0x2e, 0xbf, 0x0a, 0xff, 0xae, 0x40, 0x6b, 0x29, 0x55, 0xab, 0x9c, 0x6b, 0x54, 0x5e,
	0xc3, 0x3d, 0x93, 0x10, 0x76, 0x24, 0xd5, 0xfa, 0x52, 0xa8, 0x81, 0x97, 0x58, 0xc4, 0xe4, 0x47,
	0x08, 0xb4, 0x66, 0x7e, 0x07, 0x9c, 0xbd, 0xaf, 0x15, 0x8b, 0xfa, 0x9a, 0xc5, 0x16, 0x1c, 0x3e,
	0x81, 0xa0, 0xaf, 0x19, 0xf9, 0x02, 0xea, 0xc8, 0x69, 0xc2, 0x70, 0xe0, 0x0d, 0x21, 0x8c, 0xe6,
	0x76, 0x13, 0x15, 0x76, 0x13, 0x1d, 0x09, 0xc1, 0x9c, 0x7b, 0xc4, 0xc5, 0xaf, 0xdd, 0x04, 0xe0,
	0xaa, 0x6f, 0xc9, 0x57, 0xb0, 0x3b, 0xc8, 0xb4, 0xfd, 0x42, 0x73, 0x33, 0x7a, 0x77, 0x0f, 0xd0,
	0xd2, 0xff, 0xe4, 0x43, 0xd8, 0x36, 0x62, 0x8c, 0xdc, 0x57, 0x6a, 0x1e, 0x74, 0xff, 0xac, 0x42,
	0x63, 0xd1, 0xcf, 0xe4, 0x07, 0xf8, 0xd8, 0x8b, 0xbf, 0xa4, 0xe9, 0x18, 0x07, 0xc7, 0xe2, 0x92,
	0x6b, 0x3a, 0x91, 0xcc, 0x36, 0xf7, 0xff, 0x0b, 0xde, 0x3e, 0xd8, 0x16, 0x81, 0x72, 0xca, 0x66,
	0x3a, 0xd3, 0x3e, 0x81, 0x45, 0x7c, 0x95, 0x59, 0x50, 0xca, 0xcc, 0x8e, 0x60, 0x62, 0x78, 0x86,
	0x53, 0x64, 0xbe, 0x9c, 0x8b, 0x98, 0x3c, 0x83, 0x86, 0x42, 0x2d, 0x72, 0x95, 0xa2, 0xf6, 0xbe,
	0xb0, 0x77, 0x7b, 0xf1, 0xac, 0x5d, 0x47, 0x71, 0xf1, 0x7f, 0x7c, 0x35, 0x94, 0x8c, 0xaf, 0xb7,
	0xce, 0x7c, 0x23, 0x9c, 0xac, 0xe9, 0x87, 0x77, 0xf6, 0x0d, 0x99, 0xc0, 0x03, 0xfc, 0xc5, 0xa0,
	0xe2, 0x94, 0xd9, 0xde, 0xc9, 0x6c, 0xee, 0x75, 0xa7, 0xf7, 0xf5, 0xca, 0x7a, 0x27, 0xd7, 0x40,
	0xf1, 0x7f, 0xd0, 0xb6, 0xb1, 0x06, 0x74, 0xd6, 0x37, 0x28, 0xdb, 0x3b, 0xae, 0x0f, 0x8b, 0x30,
	0x7c, 0x73, 0x43, 0xd7, 0xb8, 0x1e, 0xae, 0xdc, 0xd0, 0xc3, 0x5b, 0xa5, 0x1e, 0x7e, 0x08, 0xa0,
	0x31, 0x55, 0x68, 0x9e, 0x65, 0x0c, 0x7d, 0xb5, 0x4a, 0x6f, 0xba, 0xbf, 0x6d, 0xc3, 0x07, 0x37,
	0x24, 0x47, 0x2e, 0x60, 0x67, 0x82, 0x86, 0x0e, 0xa8, 0xa1, 0x7e, 0x17, 0x7d, 0xbb, 0xf1, 0x8c,
	0xa3, 0xef, 0xd0, 0xd0, 0x63, 0x6a, 0x68, 0xbc, 0x60, 0x93, 0x1c, 0x5a, 0xa9, 0x2b, 0x44, 0xae,
	0xa8, 0xc9, 0x04, 0xf7, 0x5e, 0x7b, 0xbe, 0xb9, 0xd8, 0xd3, 0x32, 0x36, 0x5e, 0x56, 0x21, 0x23,
	0xa8, 0x5f, 0x62, 0x32, 0x12, 0x62, 0xdc, 0x0e, 0x3a, 0xc1, 0x5e, 0xf3, 0xd1, 0x8b, 0xcd, 0x05,
	0xdf, 0xcc, 0x81, 0x27, 0xdc, 0xa8, 0x59, 0x5c, 0xe0, 0xc3, 0x11, 0xec, 0x14, 0xd3, 0x5e, 0xcf,
	0x53, 0xee, 0x6b, 0xd7, 0xe1, 0xaf, 0xd0, 0x5a, 0x9a, 0xf3, 0x9a, 0x72, 0x1d, 0x68, 0x7a, 0x3b,
	0x7f, 0x41, 0x27, 0xe8, 0x55, 0xcb, 0xaf, 0xec, 0xb9, 0x20, 0x51, 0x65, 0x62, 0xe0, 0xe5, 0x7d,
	0x14, 0x1e, 0xc2, 0x6e, 0x79, 0x0d, 0xec, 0x79, 0x3a, 0xc6, 0x59, 0x71, 0x9e, 0x8e, 0x71, 0x66,
	0x6d, 0xc3, 0xdd, 0xfa, 0x0a, 0x43, 0x73, 0xc1, 0xe1, 0xd6, 0xe3, 0x4a, 0xf7, 0x8f, 0x2d, 0x68,
	0x2d, 0xdd, 0x2a, 0x88, 0xb8, 0xde, 0xe8, 0xf3, 0x39, 0x9c, 0x6e, 0x70, 0x53, 0xb9, 0xbb, 0xd9,
	0x7f, 0x86, 0xda, 0xbb, 0x4c, 0x8e, 0xb3, 0x62, 0x0f, 0x3e, 0xdf, 0x44, 0xe9, 0xad, 0x23, 0x15,
	0xf7, 0xc1, 0x39, 0x37, 0x3c, 0x58, 0xb3, 0x8b, 0xc3, 0x4f, 0x60, 0xb7, 0x0c, 0xbc, 0xb2, 0xdf,
	0x4a, 0xf9, 0x60, 0xf8, 0x14, 0x5a, 0x4b, 0x77, 0xa7, 0x5b, 0x7e, 0x6b, 0x42, 0x63, 0x71, 0x13,
	0x3a, 0xfa, 0xf2, 0xed, 0xc1, 0x30, 0x33, 0xa3, 0x3c, 0xb1, 0xa6, 0xdb, 0x5b, 0x4c, 0xb8, 0x47,
	0x65, 0xd6, 0xbb, 0xfb, 0xfe, 0x9e, 0xd4, 0xdc, 0x2e, 0xfa, 0xfc, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x46, 0xc4, 0x34, 0x1c, 0xe8, 0x0b, 0x00, 0x00,
}
