version: 2.1

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    working_directory: /home/circleci/api
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      # TODO(dio): Execute lint-all.
      - run: make
