// Code generated by protoc-gen-go. DO NOT EDIT.
// source: component.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/tetrateio/tetrate/api/operator/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TsbComponentSpec defines the desired installed state of TSB components.
type TsbComponentSetSpec struct {
	Base                 *BaseComponentSpec `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ApiServer            *ComponentSpec     `protobuf:"bytes,2,opt,name=api_server,json=apiServer,proto3" json:"api_server,omitempty"`
	IamServer            *ComponentSpec     `protobuf:"bytes,3,opt,name=iam_server,json=iamServer,proto3" json:"iam_server,omitempty"`
	WebUi                *ComponentSpec     `protobuf:"bytes,4,opt,name=web_ui,json=webUi,proto3" json:"web_ui,omitempty"`
	FrontEnvoy           *ComponentSpec     `protobuf:"bytes,5,opt,name=front_envoy,json=frontEnvoy,proto3" json:"front_envoy,omitempty"`
	SpmServer            *ComponentSpec     `protobuf:"bytes,6,opt,name=spm_server,json=spmServer,proto3" json:"spm_server,omitempty"`
	SpmSync              *ComponentSpec     `protobuf:"bytes,7,opt,name=spm_sync,json=spmSync,proto3" json:"spm_sync,omitempty"`
	TeamSync             *ComponentSpec     `protobuf:"bytes,8,opt,name=team_sync,json=teamSync,proto3" json:"team_sync,omitempty"`
	Ldap                 *ComponentSpec     `protobuf:"bytes,9,opt,name=ldap,proto3" json:"ldap,omitempty"`
	Oap                  *ComponentSpec     `protobuf:"bytes,10,opt,name=oap,proto3" json:"oap,omitempty"`
	Postgres             *ComponentSpec     `protobuf:"bytes,11,opt,name=postgres,proto3" json:"postgres,omitempty"`
	Elasticsearch        *ComponentSpec     `protobuf:"bytes,12,opt,name=elasticsearch,proto3" json:"elasticsearch,omitempty"`
	Zipkin               *ComponentSpec     `protobuf:"bytes,13,opt,name=zipkin,proto3" json:"zipkin,omitempty"`
	Health               *ComponentSpec     `protobuf:"bytes,14,opt,name=health,proto3" json:"health,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TsbComponentSetSpec) Reset()         { *m = TsbComponentSetSpec{} }
func (m *TsbComponentSetSpec) String() string { return proto.CompactTextString(m) }
func (*TsbComponentSetSpec) ProtoMessage()    {}
func (*TsbComponentSetSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_46d0c32769b258ba, []int{0}
}

func (m *TsbComponentSetSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TsbComponentSetSpec.Unmarshal(m, b)
}
func (m *TsbComponentSetSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TsbComponentSetSpec.Marshal(b, m, deterministic)
}
func (m *TsbComponentSetSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TsbComponentSetSpec.Merge(m, src)
}
func (m *TsbComponentSetSpec) XXX_Size() int {
	return xxx_messageInfo_TsbComponentSetSpec.Size(m)
}
func (m *TsbComponentSetSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_TsbComponentSetSpec.DiscardUnknown(m)
}

var xxx_messageInfo_TsbComponentSetSpec proto.InternalMessageInfo

func (m *TsbComponentSetSpec) GetBase() *BaseComponentSpec {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *TsbComponentSetSpec) GetApiServer() *ComponentSpec {
	if m != nil {
		return m.ApiServer
	}
	return nil
}

func (m *TsbComponentSetSpec) GetIamServer() *ComponentSpec {
	if m != nil {
		return m.IamServer
	}
	return nil
}

func (m *TsbComponentSetSpec) GetWebUi() *ComponentSpec {
	if m != nil {
		return m.WebUi
	}
	return nil
}

func (m *TsbComponentSetSpec) GetFrontEnvoy() *ComponentSpec {
	if m != nil {
		return m.FrontEnvoy
	}
	return nil
}

func (m *TsbComponentSetSpec) GetSpmServer() *ComponentSpec {
	if m != nil {
		return m.SpmServer
	}
	return nil
}

func (m *TsbComponentSetSpec) GetSpmSync() *ComponentSpec {
	if m != nil {
		return m.SpmSync
	}
	return nil
}

func (m *TsbComponentSetSpec) GetTeamSync() *ComponentSpec {
	if m != nil {
		return m.TeamSync
	}
	return nil
}

func (m *TsbComponentSetSpec) GetLdap() *ComponentSpec {
	if m != nil {
		return m.Ldap
	}
	return nil
}

func (m *TsbComponentSetSpec) GetOap() *ComponentSpec {
	if m != nil {
		return m.Oap
	}
	return nil
}

func (m *TsbComponentSetSpec) GetPostgres() *ComponentSpec {
	if m != nil {
		return m.Postgres
	}
	return nil
}

func (m *TsbComponentSetSpec) GetElasticsearch() *ComponentSpec {
	if m != nil {
		return m.Elasticsearch
	}
	return nil
}

func (m *TsbComponentSetSpec) GetZipkin() *ComponentSpec {
	if m != nil {
		return m.Zipkin
	}
	return nil
}

func (m *TsbComponentSetSpec) GetHealth() *ComponentSpec {
	if m != nil {
		return m.Health
	}
	return nil
}

// Configuration for base component.
type BaseComponentSpec struct {
	// Selects whether this component is installed.
	Enabled              *BoolValueForPB `protobuf:"bytes,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *BaseComponentSpec) Reset()         { *m = BaseComponentSpec{} }
func (m *BaseComponentSpec) String() string { return proto.CompactTextString(m) }
func (*BaseComponentSpec) ProtoMessage()    {}
func (*BaseComponentSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_46d0c32769b258ba, []int{1}
}

func (m *BaseComponentSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseComponentSpec.Unmarshal(m, b)
}
func (m *BaseComponentSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseComponentSpec.Marshal(b, m, deterministic)
}
func (m *BaseComponentSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseComponentSpec.Merge(m, src)
}
func (m *BaseComponentSpec) XXX_Size() int {
	return xxx_messageInfo_BaseComponentSpec.Size(m)
}
func (m *BaseComponentSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseComponentSpec.DiscardUnknown(m)
}

var xxx_messageInfo_BaseComponentSpec proto.InternalMessageInfo


// Configuration for internal components.
type ComponentSpec struct {
	// Selects whether this component is installed.
	Enabled *BoolValueForPB `protobuf:"bytes,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Namespace for the component. If left empty, this will default to top level namespace
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Hub for the component (overrides top level hub setting).
	Hub string `protobuf:"bytes,3,opt,name=hub,proto3" json:"hub,omitempty"`
	// Tag for the component (overrides top level tag setting).
	Tag string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	// Arbitrary install time configuration for the component.
	Spec interface{} `protobuf:"bytes,30,opt,name=spec,proto3" json:"spec,omitempty"`
	// Kubernetes resource spec.
	K8S                  *KubernetesResourcesSpec `protobuf:"bytes,50,opt,name=k8s,proto3" json:"k8s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ComponentSpec) Reset()         { *m = ComponentSpec{} }
func (m *ComponentSpec) String() string { return proto.CompactTextString(m) }
func (*ComponentSpec) ProtoMessage()    {}
func (*ComponentSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_46d0c32769b258ba, []int{2}
}

func (m *ComponentSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentSpec.Unmarshal(m, b)
}
func (m *ComponentSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentSpec.Marshal(b, m, deterministic)
}
func (m *ComponentSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentSpec.Merge(m, src)
}
func (m *ComponentSpec) XXX_Size() int {
	return xxx_messageInfo_ComponentSpec.Size(m)
}
func (m *ComponentSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentSpec proto.InternalMessageInfo


func (m *ComponentSpec) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ComponentSpec) GetHub() string {
	if m != nil {
		return m.Hub
	}
	return ""
}

func (m *ComponentSpec) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}


func (m *ComponentSpec) GetK8S() *KubernetesResourcesSpec {
	if m != nil {
		return m.K8S
	}
	return nil
}

// KubernetesResourcesConfig is a common set of k8s resource configs for components.
// This spec should eventually replace the values.yaml of the helm template
type KubernetesResourcesSpec struct {
	// Deployment environment variables.
	// https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
	Env []*common.EnvVar `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty"`
	// k8s imagePullPolicy.
	// https://kubernetes.io/docs/concepts/containers/images/
	ImagePullPolicy string `protobuf:"bytes,4,opt,name=image_pull_policy,json=imagePullPolicy,proto3" json:"image_pull_policy,omitempty"`
	// k8s pod annotations.
	// https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
	PodAnnotations map[string]string `protobuf:"bytes,7,rep,name=pod_annotations,json=podAnnotations,proto3" json:"pod_annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// k8s readinessProbe settings.
	// https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
	// k8s.io.api.core.v1.Probe readiness_probe = 9;
	ReadinessProbe *common.ReadinessProbe `protobuf:"bytes,9,opt,name=readiness_probe,json=readinessProbe,proto3" json:"readiness_probe,omitempty"`
	// k8s Deployment replicas setting.
	// https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
	ReplicaCount uint32 `protobuf:"varint,10,opt,name=replica_count,json=replicaCount,proto3" json:"replica_count,omitempty"`
	// k8s resources settings.
	// https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#resource-requests-and-limits-of-pod-and-container
	Resources *common.Resources `protobuf:"bytes,11,opt,name=resources,proto3" json:"resources,omitempty"`
	// k8s Service settings.
	// https://kubernetes.io/docs/concepts/services-networking/service/
	Service *common.ServiceSpec `protobuf:"bytes,12,opt,name=service,proto3" json:"service,omitempty"`
	// k8s deployment strategy.
	// https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
	Strategy *common.DeploymentStrategy `protobuf:"bytes,13,opt,name=strategy,proto3" json:"strategy,omitempty"`
	// k8s service annotations.
	// https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
	ServiceAnnotations   map[string]string `protobuf:"bytes,15,rep,name=service_annotations,json=serviceAnnotations,proto3" json:"service_annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *KubernetesResourcesSpec) Reset()         { *m = KubernetesResourcesSpec{} }
func (m *KubernetesResourcesSpec) String() string { return proto.CompactTextString(m) }
func (*KubernetesResourcesSpec) ProtoMessage()    {}
func (*KubernetesResourcesSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_46d0c32769b258ba, []int{3}
}

func (m *KubernetesResourcesSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesResourcesSpec.Unmarshal(m, b)
}
func (m *KubernetesResourcesSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesResourcesSpec.Marshal(b, m, deterministic)
}
func (m *KubernetesResourcesSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesResourcesSpec.Merge(m, src)
}
func (m *KubernetesResourcesSpec) XXX_Size() int {
	return xxx_messageInfo_KubernetesResourcesSpec.Size(m)
}
func (m *KubernetesResourcesSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesResourcesSpec.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesResourcesSpec proto.InternalMessageInfo

func (m *KubernetesResourcesSpec) GetEnv() []*common.EnvVar {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetImagePullPolicy() string {
	if m != nil {
		return m.ImagePullPolicy
	}
	return ""
}

func (m *KubernetesResourcesSpec) GetPodAnnotations() map[string]string {
	if m != nil {
		return m.PodAnnotations
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetReadinessProbe() *common.ReadinessProbe {
	if m != nil {
		return m.ReadinessProbe
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetReplicaCount() uint32 {
	if m != nil {
		return m.ReplicaCount
	}
	return 0
}

func (m *KubernetesResourcesSpec) GetResources() *common.Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetService() *common.ServiceSpec {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetStrategy() *common.DeploymentStrategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

func (m *KubernetesResourcesSpec) GetServiceAnnotations() map[string]string {
	if m != nil {
		return m.ServiceAnnotations
	}
	return nil
}



func init() {
	proto.RegisterType((*TsbComponentSetSpec)(nil), "tetrate.api.tsboperator.v1alpha1.TsbComponentSetSpec")
	proto.RegisterType((*BaseComponentSpec)(nil), "tetrate.api.tsboperator.v1alpha1.BaseComponentSpec")
	proto.RegisterType((*ComponentSpec)(nil), "tetrate.api.tsboperator.v1alpha1.ComponentSpec")
	proto.RegisterType((*KubernetesResourcesSpec)(nil), "tetrate.api.tsboperator.v1alpha1.KubernetesResourcesSpec")
	proto.RegisterMapType((map[string]string)(nil), "tetrate.api.tsboperator.v1alpha1.KubernetesResourcesSpec.PodAnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "tetrate.api.tsboperator.v1alpha1.KubernetesResourcesSpec.ServiceAnnotationsEntry")
}

func init() { proto.RegisterFile("component.proto", fileDescriptor_46d0c32769b258ba) }

var fileDescriptor_46d0c32769b258ba = []byte{
	// 811 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0x51, 0x6f, 0xdb, 0x36,
	0x10, 0xc7, 0x91, 0x38, 0xb1, 0xad, 0x4b, 0x1d, 0xaf, 0x4c, 0x81, 0x0a, 0xc1, 0x30, 0x04, 0x2e,
	0x30, 0x04, 0x1b, 0x60, 0xa3, 0xe9, 0x06, 0x64, 0x7b, 0x18, 0x16, 0xa7, 0x69, 0xb1, 0x65, 0x2b,
	0x3c, 0x25, 0xed, 0xc3, 0x5e, 0x0c, 0x8a, 0xbe, 0xda, 0x84, 0x25, 0x92, 0x20, 0x29, 0x17, 0xda,
	0xe3, 0xbe, 0xd2, 0xbe, 0xc0, 0xbe, 0xc4, 0xbe, 0xcf, 0x40, 0x9a, 0x72, 0xe6, 0xb9, 0x8d, 0x37,
	0x01, 0x7d, 0x23, 0x4f, 0xbc, 0xdf, 0xf1, 0xee, 0x74, 0x7f, 0x09, 0xba, 0x4c, 0xe6, 0x4a, 0x0a,
	0x14, 0xb6, 0xaf, 0xb4, 0xb4, 0x92, 0x9c, 0x58, 0xb4, 0x9a, 0x5a, 0xec, 0x53, 0xc5, 0xfb, 0xd6,
	0xa4, 0x52, 0xa1, 0xa6, 0x56, 0xea, 0xfe, 0xe2, 0x29, 0xcd, 0xd4, 0x8c, 0x3e, 0x3d, 0x3e, 0xa9,
	0x4c, 0x03, 0x26, 0xf3, 0x5c, 0x8a, 0xc1, 0xbc, 0x48, 0x51, 0x0b, 0xb4, 0x68, 0x96, 0x8c, 0xde,
	0x9f, 0x6d, 0x38, 0xba, 0x35, 0xe9, 0x65, 0x85, 0xbe, 0x41, 0x7b, 0xa3, 0x90, 0x91, 0x97, 0xb0,
	0x97, 0x52, 0x83, 0xf1, 0xce, 0xc9, 0xce, 0xe9, 0xc1, 0xd9, 0xb3, 0xfe, 0xb6, 0x50, 0xfd, 0x21,
	0x35, 0x78, 0x47, 0x51, 0xc8, 0x12, 0x0f, 0x20, 0xaf, 0x00, 0xa8, 0xe2, 0x63, 0x83, 0x7a, 0x81,
	0x3a, 0xde, 0xf5, 0xb8, 0xc1, 0x76, 0xdc, 0x3a, 0x2a, 0xa2, 0x8a, 0xdf, 0x78, 0x82, 0xe3, 0x71,
	0x9a, 0x57, 0xbc, 0x46, 0x4d, 0x1e, 0xa7, 0x79, 0xe0, 0xbd, 0x80, 0xe6, 0x3b, 0x4c, 0xc7, 0x05,
	0x8f, 0xf7, 0xea, 0xb1, 0xf6, 0xdf, 0x61, 0xfa, 0x9a, 0x93, 0x11, 0x1c, 0xbc, 0xd5, 0x52, 0xd8,
	0x31, 0x8a, 0x85, 0x2c, 0xe3, 0xfd, 0x7a, 0x30, 0xf0, 0x8c, 0x2b, 0x87, 0x70, 0x99, 0x1a, 0xb5,
	0xca, 0xb4, 0x59, 0x33, 0x53, 0xa3, 0xaa, 0x4c, 0x7f, 0x84, 0xb6, 0xe7, 0x95, 0x82, 0xc5, 0xad,
	0x7a, 0xb4, 0x96, 0xa3, 0x95, 0x82, 0x91, 0x9f, 0x20, 0xb2, 0x48, 0x03, 0xac, 0x5d, 0x0f, 0xd6,
	0x76, 0x04, 0x4f, 0xbb, 0x84, 0xbd, 0x6c, 0x42, 0x55, 0x1c, 0xd5, 0x03, 0x79, 0x67, 0x72, 0x01,
	0x0d, 0x49, 0x55, 0x0c, 0xf5, 0x18, 0xce, 0x97, 0x5c, 0x43, 0x5b, 0x49, 0x63, 0xa7, 0x1a, 0x4d,
	0x7c, 0x50, 0x33, 0xa9, 0x0a, 0x40, 0x5e, 0x43, 0x07, 0x33, 0x6a, 0x2c, 0x67, 0x06, 0xa9, 0x66,
	0xb3, 0xf8, 0x41, 0x3d, 0xe2, 0x3a, 0x85, 0xbc, 0x84, 0xe6, 0x6f, 0x5c, 0xcd, 0xb9, 0x88, 0x3b,
	0xf5, 0x78, 0xc1, 0xdd, 0x81, 0x66, 0x48, 0x33, 0x3b, 0x8b, 0x0f, 0x6b, 0x82, 0x96, 0xee, 0x3d,
	0x06, 0x0f, 0x37, 0x86, 0x9f, 0xbc, 0x82, 0x16, 0x0a, 0x9a, 0x66, 0x38, 0x09, 0x12, 0xf2, 0xd5,
	0x76, 0xfc, 0x6d, 0xa9, 0x70, 0x28, 0x65, 0xf6, 0x86, 0x66, 0x05, 0xbe, 0x90, 0x7a, 0x34, 0x4c,
	0x2a, 0x48, 0xef, 0x8f, 0x5d, 0xe8, 0x7c, 0xd4, 0x08, 0xe4, 0x53, 0x88, 0x04, 0xcd, 0xd1, 0x28,
	0xca, 0xd0, 0xeb, 0x54, 0x94, 0xdc, 0x19, 0xc8, 0x27, 0xd0, 0x98, 0x15, 0xa9, 0xd7, 0x9b, 0x28,
	0x71, 0x4b, 0x67, 0xb1, 0x74, 0xea, 0x55, 0x23, 0x4a, 0xdc, 0xd2, 0xbd, 0xc6, 0x46, 0x21, 0x8b,
	0x3f, 0xfb, 0xaf, 0xf5, 0x74, 0xd7, 0xf9, 0x41, 0x58, 0xd4, 0x6f, 0x29, 0xc3, 0xc4, 0x3b, 0x93,
	0x6b, 0x68, 0xcc, 0xcf, 0x4d, 0x7c, 0xe6, 0x19, 0xdf, 0x6c, 0x67, 0x5c, 0xaf, 0x14, 0x3d, 0x41,
	0x23, 0x0b, 0xcd, 0xd0, 0x2c, 0x5f, 0xe8, 0xf9, 0xb9, 0xe9, 0xfd, 0xd5, 0x84, 0xc7, 0x1f, 0x38,
	0x40, 0xbe, 0x86, 0x06, 0x8a, 0x45, 0xbc, 0x7b, 0xd2, 0x38, 0x3d, 0x38, 0x7b, 0xb2, 0x16, 0x68,
	0x15, 0x65, 0xf9, 0xd5, 0xe8, 0x5f, 0x89, 0xc5, 0x1b, 0xaa, 0x13, 0x77, 0x9e, 0x7c, 0x01, 0x0f,
	0x79, 0x4e, 0xa7, 0x38, 0x56, 0x45, 0x96, 0x8d, 0x95, 0xcc, 0x38, 0x2b, 0x43, 0x11, 0xba, 0xfe,
	0xc1, 0xa8, 0xc8, 0xb2, 0x91, 0x37, 0x93, 0x05, 0x74, 0x95, 0x9c, 0x8c, 0xa9, 0x10, 0xd2, 0x52,
	0xcb, 0xa5, 0x30, 0x71, 0xcb, 0x87, 0xfb, 0xb9, 0x76, 0x5e, 0xfd, 0x91, 0x9c, 0x5c, 0xdc, 0xf1,
	0xae, 0x84, 0xd5, 0x65, 0x72, 0xa8, 0xd6, 0x8c, 0xe4, 0x16, 0xba, 0x1a, 0xe9, 0x84, 0x0b, 0x34,
	0x66, 0xac, 0xb4, 0x4c, 0x31, 0x48, 0xcb, 0x97, 0xf7, 0xa6, 0x99, 0x54, 0x3e, 0x23, 0xe7, 0x92,
	0x1c, 0xea, 0xb5, 0x3d, 0x79, 0x02, 0x1d, 0x8d, 0x2a, 0xe3, 0x8c, 0x8e, 0x99, 0x2c, 0x84, 0xf5,
	0x52, 0xd3, 0x49, 0x1e, 0x04, 0xe3, 0xa5, 0xb3, 0x91, 0xe7, 0x10, 0xe9, 0xea, 0xbe, 0x41, 0x43,
	0x3e, 0xdf, 0x12, 0x34, 0x9c, 0x4e, 0xee, 0x1c, 0xc9, 0x10, 0x5a, 0x4e, 0xf6, 0x39, 0xc3, 0xa0,
	0x1a, 0xa7, 0xf7, 0x32, 0x6e, 0x96, 0x67, 0x83, 0x44, 0x2f, 0x37, 0x4e, 0xcc, 0x8c, 0x77, 0x99,
	0x96, 0xef, 0x95, 0x8a, 0x7f, 0x43, 0x9e, 0xa3, 0xca, 0x64, 0x99, 0xbb, 0xf1, 0x0a, 0x6e, 0xc9,
	0x0a, 0x40, 0x7e, 0xdf, 0x81, 0xa3, 0x00, 0x5e, 0x6b, 0x67, 0xd7, 0xb7, 0xf3, 0x97, 0xfa, 0xed,
	0x0c, 0x57, 0xdf, 0x68, 0x29, 0x31, 0x1b, 0x0f, 0x8e, 0x2f, 0xe0, 0xe8, 0x3d, 0xdd, 0x77, 0x83,
	0x38, 0xc7, 0xd2, 0x8b, 0x40, 0x94, 0xb8, 0x25, 0x79, 0x04, 0xfb, 0x0b, 0x37, 0xe1, 0x61, 0x8c,
	0x97, 0x9b, 0x6f, 0x77, 0xcf, 0x77, 0x8e, 0xaf, 0xe0, 0xf1, 0x07, 0x22, 0xfe, 0x1f, 0x4c, 0xef,
	0x11, 0x90, 0x4d, 0x29, 0xe9, 0x75, 0xa1, 0xb3, 0x36, 0xd1, 0xc3, 0xef, 0x7f, 0xfd, 0x6e, 0xca,
	0xed, 0xac, 0x48, 0x5d, 0x8d, 0x07, 0xa1, 0x46, 0x5c, 0x56, 0xab, 0x01, 0x55, 0x7c, 0xb0, 0xfa,
	0x43, 0xfb, 0x47, 0xd9, 0x06, 0x55, 0xd9, 0xd2, 0xa6, 0xff, 0x4b, 0x7b, 0xf6, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x27, 0x8f, 0xd0, 0xca, 0xfc, 0x09, 0x00, 0x00,
}
