// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: traffic_role_binding.proto

// `TrafficRoleBinding` is an assignment of roles to a set of users or
// teams to access resources under a Traffic group.  The user or team
// information is obtained from an LDAP server that should have been
// configured as part of Service Bridge installation. Note that a
// `TrafficRoleBinding` can be created or modified only by users who
// have `set_rbac` permission on the Traffic group.
//
// The following example assigns the `traffic-admin` role to users
// `alice`, `bob`, and members of the `traffic-ops` team for
// traffic group `g1` under workspace `w1` owned by the tenant
// `mycompany`.
//
// ```yaml
// apiVersion: rbac.tsb.tetrate.io/v1
// kind: TrafficRoleBinding
// metadata:
//   name: traffic-g1
//   tenant: mycompany
//   workspace: w1
//   group: g1
// spec:
//   role: traffic-admin
//   subjects:
//   - user: alice
//   - user: bob
//   - team: traffic-ops
//```
//

package v1

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// `TrafficRoleBinding` assigns permissions to users of traffic groups.
type TrafficRoleBinding struct {
	// The role being assinged to the subjects.
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// The set of users who are being assigned the role.
	Subjects             []*Subject `protobuf:"bytes,2,rep,name=subjects,proto3" json:"subjects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TrafficRoleBinding) Reset()         { *m = TrafficRoleBinding{} }
func (m *TrafficRoleBinding) String() string { return proto.CompactTextString(m) }
func (*TrafficRoleBinding) ProtoMessage()    {}
func (*TrafficRoleBinding) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf68b4987569f631, []int{0}
}
func (m *TrafficRoleBinding) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TrafficRoleBinding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TrafficRoleBinding.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TrafficRoleBinding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrafficRoleBinding.Merge(m, src)
}
func (m *TrafficRoleBinding) XXX_Size() int {
	return m.Size()
}
func (m *TrafficRoleBinding) XXX_DiscardUnknown() {
	xxx_messageInfo_TrafficRoleBinding.DiscardUnknown(m)
}

var xxx_messageInfo_TrafficRoleBinding proto.InternalMessageInfo

func (m *TrafficRoleBinding) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *TrafficRoleBinding) GetSubjects() []*Subject {
	if m != nil {
		return m.Subjects
	}
	return nil
}

func init() {
	proto.RegisterType((*TrafficRoleBinding)(nil), "tetrate.api.tsb.rbac.v1.TrafficRoleBinding")
}

func init() { proto.RegisterFile("traffic_role_binding.proto", fileDescriptor_bf68b4987569f631) }

var fileDescriptor_bf68b4987569f631 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x45, 0xe5, 0xb4, 0xa0, 0x62, 0x40, 0x42, 0x59, 0x5a, 0x75, 0x08, 0x11, 0x53, 0x07, 0x64,
	0xab, 0xb0, 0xb1, 0x91, 0x95, 0x2d, 0x30, 0xb1, 0x44, 0x76, 0xe2, 0xa4, 0x0f, 0x99, 0xbe, 0xc8,
	0x79, 0xcd, 0x0f, 0xf0, 0x07, 0x7c, 0x0e, 0x13, 0x23, 0x23, 0x9f, 0x50, 0x65, 0xe3, 0x2f, 0x50,
	0xe2, 0x94, 0x8d, 0xed, 0x4a, 0xf7, 0xbe, 0x73, 0xdf, 0xe5, 0x4b, 0x72, 0xaa, 0x2c, 0x21, 0xcf,
	0x1c, 0x5a, 0x93, 0x69, 0xd8, 0x16, 0xb0, 0xad, 0x44, 0xed, 0x90, 0x30, 0x9c, 0x93, 0x21, 0xa7,
	0xc8, 0x08, 0x55, 0x83, 0xa0, 0x46, 0x0b, 0xa7, 0x55, 0x2e, 0xda, 0xf5, 0xf2, 0xb2, 0x42, 0xac,
	0xac, 0x91, 0xaa, 0x06, 0x59, 0x82, 0xb1, 0x45, 0xa6, 0xcd, 0x46, 0xb5, 0x80, 0xce, 0x5f, 0x2e,
	0xe7, 0xad, 0xb2, 0x50, 0x28, 0x32, 0xf2, 0x20, 0x46, 0x83, 0xf7, 0x35, 0x5e, 0x5f, 0xbd, 0x31,
	0x1e, 0x3e, 0xf9, 0xf6, 0x14, 0xad, 0x49, 0x7c, 0x77, 0x18, 0xf3, 0x69, 0x1f, 0x5a, 0xb0, 0x98,
	0xad, 0x4e, 0x92, 0xb3, 0xfd, 0x7d, 0xf0, 0xf1, 0xf3, 0x39, 0x99, 0xba, 0xe0, 0x82, 0xa5, 0x83,
	0x13, 0x3e, 0xf0, 0x59, 0xb3, 0xd3, 0x2f, 0x26, 0xa7, 0x66, 0x11, 0xc4, 0x93, 0xd5, 0xe9, 0x4d,
	0x2c, 0xfe, 0x79, 0x55, 0x3c, 0xfa, 0x60, 0x72, 0x3e, 0x72, 0x8e, 0xde, 0x59, 0x30, 0x63, 0xe9,
	0x1f, 0x20, 0xb9, 0xfb, 0xea, 0x22, 0xf6, 0xdd, 0x45, 0x6c, 0xdf, 0x45, 0xec, 0xf9, 0xba, 0x02,
	0xda, 0xec, 0xb4, 0xc8, 0xf1, 0x55, 0x8e, 0x48, 0xc0, 0x83, 0x1a, 0xf6, 0x52, 0xa3, 0x65, 0x0f,
	0x97, 0xed, 0x5a, 0x1f, 0x0f, 0x43, 0x6e, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x16, 0xb7,
	0xe1, 0x45, 0x01, 0x00, 0x00,
}

func (m *TrafficRoleBinding) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TrafficRoleBinding) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TrafficRoleBinding) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Subjects) > 0 {
		for iNdEx := len(m.Subjects) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Subjects[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTrafficRoleBinding(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Role) > 0 {
		i -= len(m.Role)
		copy(dAtA[i:], m.Role)
		i = encodeVarintTrafficRoleBinding(dAtA, i, uint64(len(m.Role)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTrafficRoleBinding(dAtA []byte, offset int, v uint64) int {
	offset -= sovTrafficRoleBinding(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TrafficRoleBinding) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Role)
	if l > 0 {
		n += 1 + l + sovTrafficRoleBinding(uint64(l))
	}
	if len(m.Subjects) > 0 {
		for _, e := range m.Subjects {
			l = e.Size()
			n += 1 + l + sovTrafficRoleBinding(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovTrafficRoleBinding(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTrafficRoleBinding(x uint64) (n int) {
	return sovTrafficRoleBinding(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TrafficRoleBinding) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTrafficRoleBinding
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TrafficRoleBinding: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TrafficRoleBinding: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrafficRoleBinding
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTrafficRoleBinding
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTrafficRoleBinding
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Role = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subjects", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTrafficRoleBinding
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTrafficRoleBinding
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTrafficRoleBinding
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subjects = append(m.Subjects, &Subject{})
			if err := m.Subjects[len(m.Subjects)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTrafficRoleBinding(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTrafficRoleBinding
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTrafficRoleBinding
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTrafficRoleBinding(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTrafficRoleBinding
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrafficRoleBinding
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTrafficRoleBinding
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTrafficRoleBinding
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthTrafficRoleBinding
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowTrafficRoleBinding
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipTrafficRoleBinding(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthTrafficRoleBinding
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthTrafficRoleBinding = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTrafficRoleBinding   = fmt.Errorf("proto: integer overflow")
)
